server:
  port: 8888
  servlet:
    context-path: /jpa-demo

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/JPA_INITIAL?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: root
    password: Mysql-01
    driver-class: com.mysql.cj.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      indent-output: true
  messages:
    basename = message