DROP DATABASE IF EXISTS JPA_INITIAL;
CREATE DATABASE JPA_INITIAL;
USE JPA_INITIAL;

DROP TABLE IF EXISTS T_USER_INFO;
CREATE TABLE T_USER_INFO(
    Pk_USER_INFO_ID INT PRIMARY KEY AUTO_INCREMENT,
    USER_ACCOUNT CHAR(31) UNIQUE,
    USER_PASSWORD CHAR(31)
)DEFAULT CHARSET = "UTF8MB4";

DROP TABLE IF EXISTS T_USER_HOBBY;
CREATE TABLE T_USER_HOBBY(
    PK_USER_HOBBY_ID INT PRIMARY KEY AUTO_INCREMENT,
    USER_ACCOUNT CHAR(31),
    USER_HOBBY CHAR(31),
    FOREIGN KEY (USER_ACCOUNT)
    REFERENCES T_USER_INFO(USER_ACCOUNT)
)DEFAULT CHARSET = "UTF8MB4";