DROP DATABASE IF EXISTS JPA_INITIAL;
CREATE DATABASE JPA_INITIAL;
USE JPA_INITIAL;

CREATE TABLE T_USER_INFO(
    USER_ACCOUNT CHAR(31) PRIMARY KEY,
    USER_PASSWORD CHAR(31)
)DEFAULT CHARSET = "UTF8MB4";